// Auto generated by konsole_resource_update.ps1
using System.Collections.Generic;

class WebConsoleResource
{
	public static Dictionary<string, string> list;

	static WebConsoleResource()
	{
		list = new Dictionary<string, string>
		{
			{ "/index.html", "WebConsole/index.html" },
			{ "/css/app.204f0050.css", "WebConsole/css/app.204f0050.css" },
			{ "/fonts/flUhRq6tzZclQEJ-Vdg-IuiaDsNa.2d36eb59.woff", "WebConsole/fonts/flUhRq6tzZclQEJ-Vdg-IuiaDsNa.2d36eb59.woff" },
			{ "/fonts/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.492281ee.woff2", "WebConsole/fonts/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.492281ee.woff2" },
			{ "/fonts/KFOkCnqEu92Fr1MmgVxIIzQ.a45108d3.woff", "WebConsole/fonts/KFOkCnqEu92Fr1MmgVxIIzQ.a45108d3.woff" },
			{ "/fonts/KFOlCnqEu92Fr1MmEU9fBBc-.cea99d3e.woff", "WebConsole/fonts/KFOlCnqEu92Fr1MmEU9fBBc-.cea99d3e.woff" },
			{ "/fonts/KFOlCnqEu92Fr1MmSU5fBBc-.865f928c.woff", "WebConsole/fonts/KFOlCnqEu92Fr1MmSU5fBBc-.865f928c.woff" },
			{ "/fonts/KFOlCnqEu92Fr1MmWUlfBBc-.2267169e.woff", "WebConsole/fonts/KFOlCnqEu92Fr1MmWUlfBBc-.2267169e.woff" },
			{ "/fonts/KFOlCnqEu92Fr1MmYUtfBBc-.bac8362e.woff", "WebConsole/fonts/KFOlCnqEu92Fr1MmYUtfBBc-.bac8362e.woff" },
			{ "/fonts/KFOmCnqEu92Fr1Mu4mxM.49ae34d4.woff", "WebConsole/fonts/KFOmCnqEu92Fr1Mu4mxM.49ae34d4.woff" },
			{ "/js/3.b4e6452d.js", "WebConsole/js/3.b4e6452d.js" },
			{ "/js/4.1c2f1363.js", "WebConsole/js/4.1c2f1363.js" },
			{ "/js/app.f7bc5c21.js", "WebConsole/js/app.f7bc5c21.js" },
			{ "/js/runtime.26533f75.js", "WebConsole/js/runtime.26533f75.js" },
			{ "/js/vendor.3c22444e.js", "WebConsole/js/vendor.3c22444e.js" },
			{ "/statics/icons/favicon-128x128.png", "WebConsole/statics/icons/favicon-128x128.png" },
			{ "/statics/icons/favicon-16x16.png", "WebConsole/statics/icons/favicon-16x16.png" },
			{ "/statics/icons/favicon-32x32.png", "WebConsole/statics/icons/favicon-32x32.png" },
			{ "/statics/icons/favicon-96x96.png", "WebConsole/statics/icons/favicon-96x96.png" },
			{ "/statics/icons/favicon.ico", "WebConsole/statics/icons/favicon.ico" },
			{ "/statics/img/avatar.jpg", "WebConsole/statics/img/avatar.jpg" },
		};
	}

	public static IEnumerator<KeyValuePair<string, string>> GetEnumerator()
	{
		foreach(var kvp in list)
		{
			yield return kvp;
		}
	}
}
